# Generated by Django 3.0.3 on 2020-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tez', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yukDengeleyici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=300)),
            ],
        ),
    ]
