# Generated by Django 3.0.3 on 2020-05-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tez', '0002_yukdengeleyici'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
