# Generated by Django 3.0.3 on 2020-05-02 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tez', '0003_auto_20200502_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='yukdengeleyici',
            name='algoritma',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yukdengeleyici',
            name='svr1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yukdengeleyici',
            name='svr2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yukdengeleyici',
            name='port',
            field=models.CharField(max_length=100),
        ),
    ]
