# Generated by Django 3.0.3 on 2020-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tez', '0004_auto_20200502_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='guvenlikDuvari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldiri', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='yukdengeleyici',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
