# Generated by Django 3.0.3 on 2020-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tez', '0005_auto_20200507_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guvenlikduvari',
            old_name='saldiri',
            new_name='wafAdi',
        ),
        migrations.AddField(
            model_name='guvenlikduvari',
            name='sql',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guvenlikduvari',
            name='traversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guvenlikduvari',
            name='waf_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guvenlikduvari',
            name='xss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guvenlikduvari',
            name='yukdengeleyici_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
